"""bab

Revision ID: 0cf7ad5641e4
Revises: 28cc5df9614f
Create Date: 2026-03-07 00:10:11.664590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf7ad5641e4'
down_revision = '28cc5df9614f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materi_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['materi_id'], ['materi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bab')
    # ### end Alembic commands ###
