"""examPlan

Revision ID: 1fbaa14dd307
Revises: eac4ecd989e2
Create Date: 2026-03-07 00:15:45.532105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbaa14dd307'
down_revision = 'eac4ecd989e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materi_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('UH', 'UTS', 'UAS', 'TRYOUT'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['materi_id'], ['materi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_plans')
    # ### end Alembic commands ###
