"""materi

Revision ID: 28cc5df9614f
Revises: c4c87a2ba157
Create Date: 2026-03-07 00:08:51.490538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cc5df9614f'
down_revision = 'c4c87a2ba157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapel_id', sa.Integer(), nullable=True),
    sa.Column('kelas', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Enum('ganjil', 'genap'), nullable=True),
    sa.Column('versi', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mapel_id'], ['mapel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materi')
    # ### end Alembic commands ###
