"""question

Revision ID: 523d9db0b1a6
Revises: 8dadb164f228
Create Date: 2026-03-07 00:27:07.581307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523d9db0b1a6'
down_revision = '8dadb164f228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_version_id', sa.Integer(), nullable=True),
    sa.Column('indikator_id', sa.Integer(), nullable=True),
    sa.Column('question_bank_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('PG', 'ESSAY'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_version_id'], ['exam_versions.id'], ),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
