"""generationlogs

Revision ID: 66efcd89faab
Revises: 9f431edd8132
Create Date: 2026-03-07 00:35:38.156477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66efcd89faab'
down_revision = '9f431edd8132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('indikator_id', sa.Integer(), nullable=True),
    sa.Column('exam_version_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed'), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_version_id'], ['exam_versions.id'], ),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_logs')
    # ### end Alembic commands ###
