"""examVersion

Revision ID: 762a9360724c
Revises: 85ebbbdc6dd1
Create Date: 2026-03-07 00:20:58.125470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762a9360724c'
down_revision = '85ebbbdc6dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_plan_id', sa.Integer(), nullable=True),
    sa.Column('material_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_pg', sa.Integer(), nullable=True),
    sa.Column('total_essay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_plan_id'], ['exam_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_versions')
    # ### end Alembic commands ###
