"""examPlanChapter

Revision ID: 85ebbbdc6dd1
Revises: 1fbaa14dd307
Create Date: 2026-03-07 00:17:57.202059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ebbbdc6dd1'
down_revision = '1fbaa14dd307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_plan_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_plan_id', sa.Integer(), nullable=True),
    sa.Column('bab_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bab_id'], ['bab.id'], ),
    sa.ForeignKeyConstraint(['exam_plan_id'], ['exam_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_plan_chapters')
    # ### end Alembic commands ###
