"""questionBank

Revision ID: 8dadb164f228
Revises: 762a9360724c
Create Date: 2026-03-07 00:24:31.056733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dadb164f228'
down_revision = '762a9360724c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indikator_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('pg', 'essay'), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indikator_id'], ['indikator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_bank')
    # ### end Alembic commands ###
