"""mapel

Revision ID: b258a714b699
Revises: a250845a028e
Create Date: 2026-03-06 23:55:46.637026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b258a714b699'
down_revision = 'a250845a028e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_mapel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapel')
    # ### end Alembic commands ###
