"""indikator

Revision ID: eac4ecd989e2
Revises: 0cf7ad5641e4
Create Date: 2026-03-07 00:11:34.610095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac4ecd989e2'
down_revision = '0cf7ad5641e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indikator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bab_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cognitive_level', sa.Enum('C1', 'C2', 'C3', 'C4', 'C5', 'C6'), nullable=True),
    sa.Column('allow_pg', sa.Boolean(), nullable=True),
    sa.Column('allow_essay', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bab_id'], ['bab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indikator')
    # ### end Alembic commands ###
